# Generated by Django 4.0 on 2021-12-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
