# Generated by Django 4.0 on 2022-02-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='wiki/wikisections/', verbose_name='Иллюстрация')),
            ],
            options={
                'verbose_name': 'Вики раздел',
                'verbose_name_plural': 'Вики разделы',
            },
        ),
    ]
