# Generated by Django 4.0 on 2021-12-29 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoutUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='наименование')),
                ('need_amount', models.BooleanField(default=1, help_text='Установите флажок, если мерной единице требуется указание какой-либо количественной суммы. Например, для мерной ед. "по вкусу" указание суммы не требуется.', verbose_name='количественная')),
            ],
            options={
                'verbose_name': 'мерная единица',
                'verbose_name_plural': 'мерные единицы',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'кухня',
                'verbose_name_plural': 'кухни',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='наименование')),
                ('slug', models.SlugField(blank=True, help_text='Заполняется автоматически.', unique=True)),
                ('cooking_time', models.DurationField(null=True, verbose_name='время приготовления')),
                ('image', models.ImageField(upload_to='recipes/recipe/', verbose_name='фотография готового блюда')),
                ('description', models.TextField(verbose_name='описание блюда')),
                ('is_published', models.BooleanField(blank=True, default=0, verbose_name='опубликован')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='автор')),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.cuisine', verbose_name='кухня')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.menu', verbose_name='меню')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/recipesteps/', verbose_name='иллюстрация')),
                ('description', models.TextField(max_length=5000, verbose_name='описание')),
                ('recipe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'шаг',
                'verbose_name_plural': 'шаги',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='сумма')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wiki.ingredient', verbose_name='ингредиент')),
                ('recipe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='рецепт')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.amoutunit', verbose_name='мерная единица')),
            ],
            options={
                'verbose_name': 'ингредиент (рецепты)',
                'verbose_name_plural': 'ингредиенты (рецепты)',
            },
        ),
    ]
