# Generated by Django 4.0 on 2021-12-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmoutUnits',
            new_name='AmoutUnit',
        ),
    ]
