# Generated by Django 4.0 on 2022-01-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options_user_is_confirmed_and_more'),
        ('wiki', '0002_alter_ingredient_options_and_more'),
        ('recipes', '0002_recipe_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amoutunit',
            options={'verbose_name': 'Мерная единица', 'verbose_name_plural': 'Мерные единицы'},
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name': 'Кухня', 'verbose_name_plural': 'Кухни'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиент (рецепты)', 'verbose_name_plural': 'Ингредиенты (рецепты)'},
        ),
        migrations.AlterModelOptions(
            name='recipestep',
            options={'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.AlterField(
            model_name='amoutunit',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='amoutunit',
            name='need_amount',
            field=models.BooleanField(default=1, help_text='Установите флажок, если мерной единице требуется указание какой-либо количественной суммы. Например, для мерной ед. "по вкусу" указание суммы не требуется.', verbose_name='Количественная'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(null=True, verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.cuisine', verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/recipe/', verbose_name='Фотография готового блюда'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(blank=True, default=0, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.menu', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wiki.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.amoutunit', verbose_name='Мерная единица'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image',
            field=models.ImageField(upload_to='recipes/recipesteps/', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
