# Generated by Django 4.0 on 2022-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_amoutunit_options_alter_cuisine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.TimeField(null=True, verbose_name='Время приготовления'),
        ),
    ]
