# Generated by Django 3.2.8 on 2021-12-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_delete_cuisine_delete_menu'),
        ('recipes', '0003_auto_20211212_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wiki.ingredient'),
        ),
    ]
