# Generated by Django 4.0 on 2022-02-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполняется автоматически.', max_length=70, unique=True),
        ),
    ]
