# Generated by Django 3.2.8 on 2021-12-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
