# Generated by Django 4.0 on 2021-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_cooking_time_alter_recipe_cuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoutunit',
            name='need_amount',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='amoutunit',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
