# Generated by Django 4.0 on 2021-12-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_amoutunit_need_amount_alter_amoutunit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amoutunit',
            name='need_amount',
            field=models.BooleanField(default=1),
        ),
    ]
