# Generated by Django 4.0 on 2021-12-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userpersonalinfo_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
